export enum CoreFeatureEnum {
    Document,
    ImageResult,
    Barcode,
    BatchBarcode,
    ImportBarcode,
    MRZ,
    EHIC,
    Check,
    LicensePlate,
    TextData,
    MedicalCertificate,
    GenericDocument,
    LicenseInfo,
    OCRConfig,
    LearnMore,
}