export enum CoreFeatureEnum {
    Document,
    FinderDocument,
    ImageResult,
    SingleBarcode,
    MultiBarcode,
    MultiARBarcode,
    ImportBarcodeImage,
    MRZ,
    EHIC,
    Check,
    LicensePlate,
    TextData,
    MedicalCertificate,
    GenericDocument,
    LicenseInfo,
    LearnMore,
    OCR_CONFIGS
}
